pipeline {
    agent {
        label 'agent1'
    }
  stages {
    stage ('Build') {
      steps {
      sh 'rm -rf ./kura_test_repo/cypress2'
      sh '''
        npm install
        '''
      }
    }
    stage ('Second') {
      agent {
        label 'agent1'
      }
      steps {
      sh ''' 
        npm install cypress
        npm install mocha
        echo $WORKPACE
        npx cypress run --spec ./kura_test_repo/cypress/integration/test.spec.js
        '''
      }
      post {
        always {
          junit 'results/cypress-report.xml'
        }
          
      }
    }
  }
} 
